apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{.Values.checkout.name}}
  name: {{.Values.checkout.name}}
spec:
  replicas: {{.Values.checkout.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.checkout.name}}
  strategy: {}
  template:
    metadata:
      annotations: 
        dapr.io/enabled: "{{.Values.checkout.dapr.enabled}}"
        dapr.io/app-id: "{{.Values.checkout.dapr.appId}}"
        dapr.io/app-port: "{{.Values.checkout.dapr.appPort}}"
      labels:
        app: {{.Values.checkout.name}}
    spec:
      containers:
      - name: api
        image: {{.Values.checkout.image.repository}}
        imagePullPolicy: {{.Values.checkout.image.pullPolicy}}
        resources: {}
        ports:
          - containerPort: {{.Values.checkout.service.port}} 
        env:
        - name: PORT
          value: "{{.Values.checkout.service.port}}"
      imagePullSecrets:
        - name: {{.Values.checkout.image.pullSecret}}
status: {}
