apiVersion: v1
kind: Service
metadata:
  name: {{.Values.checkout.name}}
  labels:
    app: {{.Values.checkout.name}}
spec:
  ports:
  - port: {{.Values.checkout.service.port}}
    protocol: TCP
  selector:
    app: {{.Values.checkout.name}}
  type: LoadBalancer
