on: [push]
name: Build&Push images to Azure Container Apps (azure-container-apps)

env:
  ACR_RESOURCE_GROUP: azure-container-apps
  AZURE_CONTAINER_REGISTRY: regcontainerapps
  DEPLOYMENT_MANIFEST_PATH: |
      ./makefile

jobs:
  buildImage:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.ACA_AZURE_CREDENTIALS }}
        - name: Build and push checkout image to ACR (${{ env.AZURE_CONTAINER_REGISTRY }})
          run: az acr build --image checkout:latest --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./checkout/Dockerfile ./checkout/
        - name: Build and push order-processor image to ACR (${{ env.AZURE_CONTAINER_REGISTRY }})
          run: az acr build --image order-processor:latest --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./order-processor/Dockerfile ./order-processor/

  deployContainerApps:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        app: [checkout, order-processor]
    steps:
        - uses: actions/checkout@v3
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.ACA_AZURE_CREDENTIALS }}
        - name: Deploy container app
          run: |
            az containerapp up \
              --name ${{ matrix.app }} \
              --resource-group ${{ secrets.ACA_RESOURCE_GROUP }} \
              --location westeurope \
              --environment 'env-container-apps-environment' \
              --image ${{ secrets.ACA_REGISTRY_LOGIN_SERVER }}/${{ matrix.app }}:latest \
              --target-port 80 \
              --ingress external \
              --query properties.configuration.ingress.fqdn \
              --registry-username ${{ secrets.ACA_REGISTRY_USERNAME }} \
              --registry-password ${{ secrets.ACA_REGISTRY_PASSWORD }} \
              --env-vars 'PORT=80'
